format: 
  dashboard:
    nav-buttons: 
      - icon: github
        href: https://github.com/NoahBolohan/wingspan-dashboard
    theme:
      - brand
      - styles.scss
    scrolling: true 
    expandable: false